# .github/workflows/update-better-control.yml
name: Update better-control commit version

on:
  schedule:
    # Runs hourly (adjust as needed, e.g., '0 8 * * *' for daily at 8 AM UTC)
    - cron: "0 * * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  update-better-control:
    runs-on: ubuntu-latest
    # Prevent multiple runs for the same commit/event
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for accurate version comparison and branch operations
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          # Use nixpkgs-unstable channel for potentially newer tools
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install dependencies (using Nix)
        run: |
          # Install necessary tools using nix profile for better isolation
          nix profile install nixpkgs#gh nixpkgs#nix-prefetch-github nixpkgs#jq nixpkgs#gnused nixpkgs#gnugrep

          # Add Nix binaries to PATH for subsequent steps
          echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH
          # Verify installation
          gh --version
          nix-prefetch-github --version
          jq --version
          sed --version || true # gnu sed might not have --version
          grep --version || true # gnu grep might not have --version

      - name: Get current and latest commit SHAs
        id: versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get current commit hash (rev) from package.nix
          # Using `|| true` to prevent the grep from failing the step if 'version' is not found,
          # and then default to a dummy hash.
          CURRENT_COMMIT_SHA=$(grep -oP 'version\s*=\s*"\K[^"]+' package.nix || echo "0000000000000000000000000000000000000000")
          echo "Current commit SHA found in package.nix: $CURRENT_COMMIT_SHA"
          echo "CURRENT_COMMIT_SHA=$CURRENT_COMMIT_SHA" >> $GITHUB_ENV

          echo "Fetching latest commit SHA from 'main' branch..."
          # Fetch the SHA of the latest commit on the 'main' branch
          LATEST_COMMIT_SHA=$(gh api repos/quantumvoid0/better-control/commits/main --jq '.sha')

          if [ -z "$LATEST_COMMIT_SHA" ] || [ "$LATEST_COMMIT_SHA" == "null" ]; then
            echo "::error::Could not extract latest commit SHA from GitHub API response for 'main' branch."
            exit 1
          fi

          echo "Latest commit SHA from 'main' branch: $LATEST_COMMIT_SHA"
          echo "LATEST_COMMIT_SHA=$LATEST_COMMIT_SHA" >> $GITHUB_ENV

          if [ "$CURRENT_COMMIT_SHA" = "$LATEST_COMMIT_SHA" ]; then
            echo "better-control is up-to-date with 'main' branch ($CURRENT_COMMIT_SHA)."
            echo "UPDATE_NEEDED=false" >> $GITHUB_ENV
          else
            echo "Update needed: $CURRENT_COMMIT_SHA -> $LATEST_COMMIT_SHA"
            echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
          fi

      - name: Check for existing Pull Request
        id: check_pr
        # Only run if an update is potentially needed
        if: env.UPDATE_NEEDED == 'true'
        env:
          # GITHUB_TOKEN needed for gh cli to interact with the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for checking PRs
          # Define branch name early using the determined LATEST_COMMIT_SHA
          BRANCH_NAME: "update-better-control-commit-${{ env.LATEST_COMMIT_SHA }}"
        run: |
          echo "Checking for existing open PR for branch: $BRANCH_NAME"
          # Use gh pr list to find open PRs targeting the default branch from the head branch
          # Ensure you replace 'main' if your default branch is different
          EXISTING_PR_URL=$(gh pr list --head "$BRANCH_NAME" --base main --state open --json url --jq '.[0].url')

          if [ -n "$EXISTING_PR_URL" ]; then
            echo "::warning::An open pull request already exists for branch $BRANCH_NAME: $EXISTING_PR_URL"
            echo "Skipping update and PR creation steps."
            echo "PR_EXISTS=true" >> $GITHUB_ENV
          else
            echo "No existing open PR found for branch $BRANCH_NAME."
            echo "PR_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Update commit SHA and hash
        if: env.UPDATE_NEEDED == 'true' && env.PR_EXISTS == 'false'
        env:
          # Pass LATEST_COMMIT_SHA to this step's environment
          LATEST_COMMIT_SHA: ${{ env.LATEST_COMMIT_SHA }}
        run: |
          echo "Updating package.nix to commit SHA (rev) $LATEST_COMMIT_SHA"

          # Update 'version' (rev) string using GNU sed
          sed -i -E "s@(version\s*=\s*\")[^\"]+@\1${LATEST_COMMIT_SHA}@" package.nix
          echo "Version (rev) updated in package.nix"

          # Run nix-prefetch-github with the LATEST_COMMIT_SHA
          echo "Running: nix-prefetch-github quantumvoid0 better-control --rev $LATEST_COMMIT_SHA"
          PREFETCH_OUTPUT=$(nix-prefetch-github quantumvoid0 better-control --rev "$LATEST_COMMIT_SHA" 2>&1)
          echo "Prefetch output:"
          echo "$PREFETCH_OUTPUT"

          NEW_HASH=""
          if echo "$PREFETCH_OUTPUT" | jq -e .hash > /dev/null 2>&1; then
            NEW_HASH=$(echo "$PREFETCH_OUTPUT" | jq -r .hash)
            echo "Extracted hash via jq: $NEW_HASH"
          else
            echo "::warning::nix-prefetch-github did not produce valid JSON output. Attempting legacy extraction."
            LEGACY_HASH=$(echo "$PREFETCH_OUTPUT" | grep -oP 'sha256-[a-zA-Z0-9/+]+=*')
            if [ -n "$LEGACY_HASH" ]; then
              NEW_HASH=$(echo "$LEGACY_HASH" | head -n 1)
              echo "Extracted legacy hash via grep: $NEW_HASH"
            else
              echo "::error::Failed to extract hash from prefetch output (JSON and Legacy methods failed)."
              echo "Output was: $PREFETCH_OUTPUT"
              exit 1
            fi
          fi

          if [[ "$NEW_HASH" =~ ^sha256-[A-Za-z0-9+/]+={0,2}$ ]]; then
            echo "Validated hash format: $NEW_HASH"
          else
            echo "::error::Extracted value '$NEW_HASH' does not look like a valid sha256 hash."
            exit 1
          fi

          # Update hash using GNU sed
          sed -i -E "s|(hash\s*=\s*\")[^\"]+(\";)|\1${NEW_HASH}\2|" package.nix

          if grep -q "hash = \"$NEW_HASH\";" package.nix; then
            echo "Successfully updated hash in package.nix"
          else
            echo "::error::Failed to verify hash update in package.nix using sed."
            echo "Expected hash line: hash = \"$NEW_HASH\";"
            echo "File content after attempted update:"
            cat package.nix
            exit 1
          fi

      # This step replaces the manual git commit and push, and the previous PR creation script
      - name: Create Pull Request with peter-evans/create-pull-request
        if: env.UPDATE_NEEDED == 'true' && env.PR_EXISTS == 'false'
        uses: peter-evans/create-pull-request@v6
        env:
          CURRENT_COMMIT_SHA: ${{ env.CURRENT_COMMIT_SHA }}
          LATEST_COMMIT_SHA: ${{ env.LATEST_COMMIT_SHA }}
          BRANCH_NAME: "update-better-control-commit-${{ env.LATEST_COMMIT_SHA }}"
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }} # Use your PAT here
          commit-message: "feat: Update better-control to latest 'main' commit ${{ env.LATEST_COMMIT_SHA }}"
          title: "feat: Update better-control to latest 'main' commit ${{ env.LATEST_COMMIT_SHA | slice(0, 7) }}" # Changed here
          body: |
            This PR automatically updates the `better-control` package from commit `${{ env.CURRENT_COMMIT_SHA | slice(0, 7) }}` to `${{ env.LATEST_COMMIT_SHA | slice(0, 7) }}`. # Changed here

            Full commit SHAs:
            - Old: `${{ env.CURRENT_COMMIT_SHA }}`
            - New: `${{ env.LATEST_COMMIT_SHA }}`

            This update fetches the latest commit from the `main` branch of the `quantumvoid0/better-control` repository.

            Changes generated by GitHub Actions workflow.
          branch: ${{ env.BRANCH_NAME }}
          base: main # The target branch for the PR
          delete-branch: true # Delete the branch after PR is merged/closed
