name: Update better-control version

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  workflow_dispatch:

jobs:
  update-better-control:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest version
        id: get_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/quantumvoid0/better-control/releases/latest | jq -r .tag_name)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Update version and sha256
        run: |
          sed -i "s/version = \"[0-9.]*\";/version = \"$LATEST_VERSION\";/" flake.nix
          NEW_SHA256=$(nix-prefetch-url --unpack "https://github.com/quantumvoid0/better-control/archive/refs/tags/$LATEST_VERSION.zip")
          sed -i "s|sha256 = \"sha256-[^"]*\";|sha256 = \"$NEW_SHA256\";|" flake.nix

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b update-better-control-$LATEST_VERSION
          git add flake.nix
          git commit -m "Update better-control to $LATEST_VERSION"
          git push origin update-better-control-$LATEST_VERSION

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Update better-control to $LATEST_VERSION" \
            --body "This updates better-control to version $LATEST_VERSION." \
            --head update-better-control-$LATEST_VERSION \
            --base main
