name: Update better-control version

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-better-control:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for checking existing PRs

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          nix profile install nixpkgs#nix-prefetch-github nixpkgs#jq

      - name: Get current and latest versions
        id: versions
        run: |
          CURRENT_VERSION=$(grep -oP 'version = "\K[0-9.]+(?=";)' package.nix)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

          LATEST_VERSION=$(curl -s https://api.github.com/repos/quantumvoid0/better-control/releases/latest | jq -r .tag_name)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

          if [ "$CURRENT_VERSION" = "$LATEST_VERSION" ]; then
            echo "UPDATE_NEEDED=false" >> $GITHUB_ENV
          else
            echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
          fi

      - name: Update version and hash
        if: env.UPDATE_NEEDED == 'true'
        run: |
          # Update version in package.nix
          sed -i "s/version = \".*\";/version = \"$LATEST_VERSION\";/" package.nix
          
          # Run nix-prefetch-github and capture all output
          echo "Running: nix-prefetch-github quantumvoid0 better-control --rev $LATEST_VERSION"
          PREFETCH_OUTPUT=$(nix-prefetch-github quantumvoid0 better-control --rev "$LATEST_VERSION" 2>&1)
          echo "Prefetch output:"
          echo "$PREFETCH_OUTPUT"
          
          # Extract hash from output
          NEW_HASH=$(echo "$PREFETCH_OUTPUT" | jq -r .hash)
          echo "Extracted hash: $NEW_HASH"
          
          if [ -z "$NEW_HASH" ]; then
            echo "::error::Failed to extract hash from prefetch output"
            exit 1
          fi
          
          # Update hash in package.nix
          sed -i "s|hash = \".*\";|hash = \"$NEW_HASH\";|" package.nix

      - name: Commit and push changes
        if: env.UPDATE_NEEDED == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          BRANCH="update-better-control-$LATEST_VERSION"
          git checkout -B "$BRANCH"
          git add package.nix
          git commit -m "Update better-control to $LATEST_VERSION"
          git push -f origin "$BRANCH"

      - name: Create or update PR
        if: env.UPDATE_NEEDED == 'true'
        run: |
          BRANCH="update-better-control-$LATEST_VERSION"
          PR_TITLE="Update better-control to $LATEST_VERSION"
          PR_BODY="Automated version update for better-control package"
          
          # Check if PR already exists
          PR_EXISTS=$(gh pr list --head "$BRANCH" --json id -q 'length')
          
          if [ "$PR_EXISTS" -eq 0 ]; then
            echo "Creating new PR"
            gh pr create \
              --title "$PR_TITLE" \
              --body "$PR_BODY" \
              --head "$BRANCH" \
              --base "main"
          else
            echo "PR already exists, updating branch"
            # The branch was already force-pushed in the previous step
            # No additional action needed as the PR will automatically update
          fi