name: Update better-control version

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:

jobs:
  update-better-control:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Get current and latest versions
        id: versions
        run: |
          # Get current version from package.nix
          CURRENT_VERSION=$(grep -oP 'version = "\K[0-9.]+(?=";)' package.nix)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          
          # Get latest version from GitHub
          LATEST_VERSION=$(curl -s https://api.github.com/repos/quantumvoid0/better-control/releases/latest | jq -r .tag_name)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          
          # Compare versions
          if [ "$CURRENT_VERSION" = "$LATEST_VERSION" ]; then
            echo "No update available (current: $CURRENT_VERSION, latest: $LATEST_VERSION)"
            echo "UPDATE_NEEDED=false" >> $GITHUB_ENV
          else
            echo "Update available (current: $CURRENT_VERSION, latest: $LATEST_VERSION)"
            echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
          fi

      - name: Update version and sha256
        if: env.UPDATE_NEEDED == 'true'
        run: |
          sed -i "s/version = \"[0-9.]*\";/version = \"$LATEST_VERSION\";/" package.nix

          NEW_SHA256=$(nix-prefetch-url --unpack "https://github.com/quantumvoid0/better-control/archive/refs/tags/$LATEST_VERSION.zip" | tail -n1)

          sed -i "s|sha256 = \".*\";|sha256 = \"$NEW_SHA256\";|" package.nix

      - name: Commit changes
        if: env.UPDATE_NEEDED == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Check if branch already exists remotely
          if git ls-remote --exit-code --heads origin update-better-control-$LATEST_VERSION; then
            echo "Branch update-better-control-$LATEST_VERSION already exists."
            echo "PR_EXISTS=true" >> $GITHUB_ENV
          else
            git checkout -b update-better-control-$LATEST_VERSION
            git add package.nix
            git commit -m "Update better-control to $LATEST_VERSION"
            git push origin update-better-control-$LATEST_VERSION || {
              echo "Push failed. Branch might already exist."
              echo "PR_EXISTS=true" >> $GITHUB_ENV
              exit 0
            }
          fi

      - name: Check for existing PR
        if: env.UPDATE_NEEDED == 'true'
        id: check-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if PR already exists
          PR_EXISTS=$(gh pr list --head "update-better-control-$LATEST_VERSION" --json number --jq 'length')
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV
          if [ "$PR_EXISTS" -gt 0 ]; then
            echo "PR already exists for this update"
          else
            echo "No existing PR found"
          fi

      - name: Create Pull Request
        if: env.UPDATE_NEEDED == 'true' && env.PR_EXISTS == '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Update better-control to $LATEST_VERSION" \
            --body "This updates better-control to version $LATEST_VERSION." \
            --head update-better-control-$LATEST_VERSION \
            --base main

      - name: Skip update or PR creation
        if: env.UPDATE_NEEDED == 'false' || (env.UPDATE_NEEDED == 'true' && env.PR_EXISTS != '0')
        run: |
          if [ "$UPDATE_NEEDED" = "false" ]; then
            echo "No update needed - current version ($CURRENT_VERSION) is up-to-date"
          else
            echo "PR already exists for version $LATEST_VERSION - skipping PR creation"
          fi